openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:

  /releases:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Release"
      responses:
        200:
          description: Release created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReleaseWithId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ReleaseWithId"
  /releases/{id}:
    get:
      parameters:
        - $ref: "#/components/parameters/ReleaseId"
      responses:
        200:
          description: Release found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReleaseWithId"
    put:
      parameters:
        - $ref: "#/components/parameters/ReleaseId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Release"
      responses:
        200:
          description: Updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReleaseWithId"
    delete:
      parameters:
        - $ref: "#/components/parameters/ReleaseId"
      responses:
        201:
          description: Deleted successfully


components:
  parameters:
    ReleaseId:
      name: id
      in: path
      required: true
      description: ID of release
      schema:
        type: string
  schemas:
    Release:
      properties:
        title:
          type: string
        albumArtist:
          type: string
        medium:
          type: string
          enum:
            - VINYL
            - CD
            - TAPE
            - DIGITAL
    ReleaseWithId:
      type: object
      properties:
        id:
          type: string
      allOf:
        - $ref: "#/components/schemas/Release"