name: folker
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: folker
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      NATS_USER: admin
      NATS_PASSWORD: secret