@startuml

actor Client
participant ReleaseController
participant ReleaseCommandHandler
participant EventPublisher
queue Nats
participant ReleaseQueryHandler
database Mongo

Client -> ReleaseController: CreateReleaseRequestDto
activate ReleaseController
ReleaseController -> ReleaseCommandHandler : CreateReleaseCommand
Client <- ReleaseController : CreateReleaseResponseDto
deactivate ReleaseController

ReleaseCommandHandler -> EventPublisher : ReleaseCreatedEvent

EventPublisher -> Nats : ReleaseCreatedEvent

Nats <- ReleaseQueryHandler : ReleaseCreatedEvent
ReleaseQueryHandler -> Mongo : Release

@enduml
